// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ProjectMVC.Models;

public partial class ForProjectContext : DbContext
{
    public ForProjectContext(DbContextOptions<ForProjectContext> options)
        : base(options)
    {
    }
    public ForProjectContext()
    {

    }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
            optionsBuilder.UseSqlServer("Server=.\\PROJECTSQL;Database=ForProject;Trusted_Connection=True;TrustServerCertificate=true;MultipleActiveResultSets=true;");
        }
    }

    public virtual DbSet<Contacts> Contacts { get; set; }

    public virtual DbSet<Projects> Projects { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Contacts>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.SubmitDate).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<Projects>(entity =>
        {
            entity.Property(e => e.CreateDate).HasDefaultValueSql("(getdate())");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}